/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Comp.WeatherAPI;

public class App {
    public static void main(String[] args) {
        String city = "London";
        String lat = "33.441792";
        String lon = "-94.037689";
        String part = "hourly,daily";
        String layer = "clouds_new";
        String z = "10";
        String x = "10";
        String y = "10";

        DateUtils dateUtils = new DateUtils();
        String date = dateUtils.getDaysAgoInSecond(4);
        System.out.println(String.format("4 days ago in ms = %s", date));
        String time = date;


        WeatherAPI weather = new WeatherAPI();
        String currentWeather = weather.getCurrentWeatherAt(city);
        String dailyForecast = weather.getDailyForecast(lat, lon, part);
        String minuteForecast = weather.getMinuteForecast(lat, lon, part);
        String historicalWeather = weather.getHistoricalWeather(lat, lon, time);
        System.out.println(String.format("currentWeather = %s", currentWeather));
        System.out.println(String.format("dailyForecast = %s", dailyForecast));
        System.out.println(String.format("minuteForecast = %s", minuteForecast));
        System.out.println(String.format("historicalWeather = %s", historicalWeather));

        weather.getBasicWeatherMap(layer, z, x, y);
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
